### ISSUE TITLE
USER STORY: local examples

### ISSUE THREAD

**Issue by MarkChips** [MarkChips/prevent-awareness#10]
In order to **learn about local examples** as a **user**, I can **find the section on the case studies page**
### Acceptance Criteria:
- quote case studies from Berkshire of successful prevent campaigns
- demonstrate how prevent has saved someone's life
- appeal to people's hearts
### Tasks:
- [ ] find prevent case studies for Berkshire
- [ ] create sections for each case study
- [ ] add profile photo for each case study
- [ ] include personal quotes from the case study subject
