### ISSUE TITLE
USER STORY: social media links

### ISSUE THREAD

**Issue by Grace-YuGuo** [MarkChips/prevent-awareness#11]
In order to **access related social media  links** as a **user**, I can **quickly connect to the social media platforms**
### Acceptance Criteria:
- Social media links can connect to correct website.
- links using the recognized icons for each social media link.

### Tasks:
- [x] Creat a elements for these link
- [x] Add icons for each a elements
- [x] Position/style these elements in css file
