### ISSUE TITLE
USER STORY: national examples

### ISSUE THREAD

**Issue by MarkChips** [MarkChips/prevent-awareness#12]
In order to **learn about national examples** as a **user**, I can **find the section on the case studies page**
### Acceptance Criteria:
- quote case studies from the UK of successful prevent campaigns
- demonstrate how prevent has saved someone's life
- appeal to people's hearts
### Tasks:
- [x] find prevent case studies from the UK
- [x] create sections for each case study
- [x] add profile photo for each case study
- [x] include personal quotes from the case study subject
