### ISSUE TITLE
USER STORY: External links to workshops

### ISSUE THREAD

**Issue by Grace-YuGuo** [MarkChips/prevent-awareness#13]
In order to *access external links to workshops** as a **user**, I can **quickly connect to the further related workshops**

### Acceptance Criteria:
- External links(buttons) can connect to the related workshops once clicked in a new tab
- 
### Tasks:
- [ ] Add a elements for the external workshop links
- [ ] Add proper icons for the a elements
- [ ] style the font size/color of these elements
