### ISSUE TITLE
USER STORY: authorities to contact

### ISSUE THREAD

**Issue by Grace-YuGuo** [MarkChips/prevent-awareness#15]
In order to **contact authorities if required** as a **user**, I can **have access to contact authorities**

### Acceptance Criteria:
- Clear list of the authorities to contact
- Once click the button/icon, expand the contact detail for each authority. 
### Tasks:
- [ ] Add ul element in HTML
- [ ] Add dropdown or summary/detail element in HTML
- [ ] Style the font /size /position, color in CSS
