### ISSUE TITLE
USER STORY: Form - contact us for advice/help whether for themself or a friend

### ISSUE THREAD

**Issue by Grace-YuGuo** [MarkChips/prevent-awareness#16]
In order to **contact for further advice/help** as a **user**, I can **leave the contact details for further correspondences**

### Acceptance Criteria:
- Clear form to fill, which includes the name/email/phone
- Once submitted, received a successful confirmation
### Tasks:
- [ ] Add form element in HTML
- [ ] Add input and label elements in HTML
- [ ] Style the color /font size/ position in CSS
