### ISSUE TITLE
Add all meta data and CDN dependencies

### ISSUE THREAD

**Issue by MarkChips** [MarkChips/prevent-awareness#20]
Tasks:
- [x] add meta description
- [x] add meta keywords
- [x] add favicon
- [x] add bootstrap 5.3 CDN
