### ISSUE TITLE
USER STORY: community initiatives

### ISSUE THREAD

**Issue by MarkChips** [MarkChips/prevent-awareness#29]
In order to **learn about community initiatives** as a **user**, I can **find the section on the resources page and  follow links to their websites**
### Acceptance Criteria:
- the community initiatives are of good repute
- there is information about the community initiatives above each link
- the information is concise
### Tasks:
- [ ] find community initiatives relating to prevent
- [ ] create divs for each community initiative
- [ ] add name title of each community initiative
- [ ] add paragraph explaining what the community initiative is about
- [ ] add link to community initiative
- [ ] wrap all divs in a responsive layout
