### ISSUE TITLE
USER STORY: principles and objectives of prevent

### ISSUE THREAD

**Issue by MarkChips** [MarkChips/prevent-awareness#6]
In order to **learn about the Principles of prevent** as a **user**, I can **go to the principles section on the homepage**
In order to **learn about the objectives of prevent** as a **user**, I can **go to the objectives section on the homepage**
### Acceptance Criteria:
- Write a concise list clearly detailing the principles of prevent
- Write a concise list clearly detailing the objectives of prevent
### Tasks:
- [x] In the left side column create a title of Principles
- [x] In the right side column create a title of Objectives
- [x] create a list under principles
- [x] create a list under objectives
