### ISSUE TITLE
USER STORY: welcome message and title

### ISSUE THREAD

**Issue by MarkChips** [MarkChips/prevent-awareness#8]
In order to **understand what website I am on** as a **user**, I can **see the welcome message and title on the homepage**
### Acceptance Criteria:
- Bold and central
- First thing user sees on homepage
- Attractive
- Makes it obvious what website is about
### Tasks:
- [ ] create h1 element in header with the website title
- [ ] create h3 element  below h1 with the welcome message explaining what the website is for
- [ ] style elements so that they stand out from rest of page
- [ ] centre text
