### ISSUE TITLE
USER STORY: how prevent operates within the wider context of counter-terrorism

### ISSUE THREAD

**Issue by MarkChips** [MarkChips/prevent-awareness#9]
In order to **understand how prevent operates within the wider context of counter-terrorism** as a **user**, I can **go to the section on the homepage**
### Acceptance Criteria:
- Include factual information sourced from the uk government's website
- Be engaging
### Tasks:
- [x] Create section above footer on homepage
- [x] Add title element
- [x] Add paragraph element with information from uk government
- [x] Allow to expand to 5/6 of the screen on medium size screens?
